#This is a Build Deploy Pipeline for .NET 6 Web App to Azure App Service using Azure DevOps Pipeline

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"
  dotNetFramework: "net6.0"
  dotNetVersion: "6.0.x"
  targetRuntime: "linux-x64"
  azureSPNName: "YOUR-SPN-NAME" #get it from your AzureDevOps portal
  azureAppServiceName: "Your-Azure-AppService-Name" #get it from your Azure portal

# Build the app for .NET 6 framework
steps:
  - task: UseDotNet@2
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true # Required for preview versions

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "**/*Test/*.csproj"
      arguments: "--configuration $(buildConfiguration)"
    displayName: "dotnet test"

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: "Build .NET 6 Application"

  - task: DotNetCoreCLI@2
    displayName: "dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: "src/SimpleAPI/SimpleAPI.csproj"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "publish artifacts"
